### ISSUE TITLE
失效了

### ISSUE THREAD

**Issue by jzhang-0** [JiangGua/classin-downloader#4]
有时间维护一下吗，失效了。

**Comment by JiangGua** [comment]
OK，可能这一两个星期会看一下

**Comment by Kirrito-k423** [comment]
大佬，修好了吗
```
classin-downloader on  master [?] via 🐍 v3.9.7
❯ python src/cli.py txt .\bb.html
Traceback (most recent call last):
  File "E:\PowerShell\github\classin-downloader\src\cli.py", line 31, in <module>
    cli()
  File "E:\commonSoftware\anaconda\lib\site-packages\click\core.py", line 1128, in __call__
    return self.main(*args, **kwargs)
  File "E:\commonSoftware\anaconda\lib\site-packages\click\core.py", line 1053, in main
    rv = self.invoke(ctx)
  File "E:\commonSoftware\anaconda\lib\site-packages\click\core.py", line 1659, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "E:\commonSoftware\anaconda\lib\site-packages\click\core.py", line 1395, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "E:\commonSoftware\anaconda\lib\site-packages\click\core.py", line 754, in invoke
    return __callback(*args, **kwargs)
  File "E:\PowerShell\github\classin-downloader\src\cli.py", line 17, in txt
    bbparser.get_bb_videos(path)
  File "E:\PowerShell\github\classin-downloader\src\bbparser.py", line 139, in get_bb_videos
    get_classin_video(key)
  File "E:\PowerShell\github\classin-downloader\src\bbparser.py", line 116, in get_classin_video
    vlist = c.videolist()
  File "E:\PowerShell\github\classin-downloader\src\bbparser.py", line 85, in videolist
    vlist = data['data']['lessonData']['vodList']
KeyError: 'data'
```
